### ISSUE TITLE
Unable to load bundled icons

### ISSUE THREAD

**Issue by fi8er1** [SimformSolutionsPvtLtd/flutter_credit_card#75]
`Unable to load asset: packages/flutter_credit_card/icons/visa.png
      #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
      <asynchronous suspension>
      #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:675:14)
      <asynchronous suspension>`

![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 04 56 37](https://user-images.githubusercontent.com/2786289/149849132-d0b786cf-b26e-4903-8c3b-1f930ecf6d70.png)

 -OS iOS
 -Version 15

**Comment by fi8er1** [comment]
...was a personal platform issue.
